### ISSUE TITLE
apps crashing crash report

### ISSUE THREAD

**Issue by 211this** [coolstar/electra-ipas#1]
[panic-full-2018-01-13-140059.539.ips.txt](https://github.com/coolstar/electra-ipas/files/1628953/panic-full-2018-01-13-140059.539.ips.txt)

**Comment by JonathanTheInsane** [comment]
The actual electra repo where you can post this issue is right here
https://github.com/coolstar/electra

**Comment by coolstar** [comment]
Please post issues in the other repo
